version: "1"
services:
  ocrfastapi:
    container_name: ocrfastapi-service # Custom Container Name
    image: ocrfastapi:latest # Customized Image Name & Label in Step 2
    volumes:
    - ./:/app/ocr-service
    ports:
     - 8005:8005
    restart: unless-stopped