version: "1"
services:
  parseqocrfastapi:
    container_name: parseqocrfastapi-service # Custom Container Name
    image: parseqocrfastapi:latest # Customized Image Name & Label in Step 2
    volumes:
     - ./:/app
    ports:
     - 8001:8001
    restart: unless-stopped