version: "1"
services:
  ocrfastapi:
    container_name: ocrfastapi-service # Custom Container Name
    image: ocrfastapi:latest # Customized Image Name & Label in Step 2
    volumes:
     - ./:/app
    ports:
     - 8000:8000
    restart: unless-stopped

networks:
  default:
    name: ocr-services